// Automatically generated by the Objective-D preprocessor
import objd.runtime;


#line 2 "test/syntax.d"
import 
std.stdio; 

/* Objective-D class object */
Class MyClass;
static this () { MyClass = new Class("MyClass", NSObject); }

#line 6 "test/syntax.d"

#line 8 "test/syntax.d"


void main ( ) { 
assert ( MyClass.msgSend!id(sel_registerName("class")) is MyClass ) 
; assert ( MyClass.msgSend!id(sel_registerName("class")) .msgSend!id(sel_registerName("superclass")) is NSObject ) 
; 
id obj = MyClass.msgSend!id(sel_registerName("new")) 
; assert ( obj !is null ) 
; assert ( obj.msgSend!id(sel_registerName("class")) is MyClass ) 
; 
MyClass.addMethod ( sel_registerName ( `copyAndPrint:also:`) , function id ( id self, SEL cmd, string a, string b ) { 
writefln ( `a: %s`, a ) 
; writefln ( `b: %s`, b ) 
; return 
self; } ) 
; 
obj.msgSend!id(sel_registerName("copyAndPrint:also:"), `hello`, `world`) 
; writeln ( `All tests passed!`) 
; } 